name: .NET Core

on: [push]

jobs:
  build-win10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: client/node_modules
        key: ${{ runner.OS }}-client-${{ hashFiles('**/client/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-client-
          ${{ runner.OS }}-

    - name: Build with dotnet
      run: |
        cd AtemServer
        dotnet publish -o "$(pwd)/dist" -c Release -r win10-x64
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: AtemServer-win10
        path: AtemServer/dist

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: client/node_modules
        key: ${{ runner.OS }}-client-${{ hashFiles('**/client/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-client-
          ${{ runner.OS }}-

    - name: Build with dotnet
      run: |
        cd AtemServer
        dotnet publish -o "$(pwd)/dist" -c Release -r linux-x64
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: AtemServer-linux
        path: AtemServer/dist
